spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

    datasource:
      #    url: jdbc:postgresql://postgis-tsodd:5432/tsodd-service
        url: jdbc:postgresql://postgis-tsodd:5432/tsodd-service
        username: postgres
        password: postgres

    liquibase:
        change-log: classpath.db/changelog/db.changelog-main.xml
        url: jdbc:postgresql://postgis-tsodd:5432/tsodd-service
        user: postgres
        password: postgres