spring:
  datasource:
    url: jdbc:postgresql://${POSTGIS_TSODD_HOST:localhost}:${POSTGIS_TSODD_PORT:5432}/${POSTGIS_TSODD_DATABASE:testDB}
    username: ${POSTGIS_TSODD_USER:postgres}
    password: ${POSTGIS_TSODD_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  data:
    rest:
      base-path: api/tsodd/v1
jwt:
  token:
    secret: ${ACCESS_TOKEN_SECRET:accessTokenSecret}
    expired: ${ACCESS_TOKEN_EXPIRATION:600}