version: "3.8"

volumes: 
  mongo_data:

services:

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on: 
      - user-service
    ports: 
      - "8080:80"

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      target: builder
    image: user-service
    expose:
      - "8080"
    environment:
      - ENV=dev
    env_file: 
      - .env
    volumes:
      - ./user-service:/go/src/app
    depends_on: 
      - user-service-mongo
    command: ./wait-for.sh ${MONGO_HOST}:${MONGO_PORT} -- reflex -r "\.go$$" -s -- sh -c "go run ./"

  user-service-mongo:
    container_name: ${MONGO_HOST}
    image: mongo
    volumes: 
      - "mongo_data:/data/db"
    expose: 
      - ${MONGO_PORT}
    command: mongod --quiet --port ${MONGO_PORT}
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
    depends_on: 
      - user-service-mongo
