version: "3.8"

services:

  nginx:
    build: ./nginx
    ports: 
      - "8080:80"

  user-service:
    build:
      context: ./user-service
      target: builder
    image: user-service
    expose:
      - "8080"
    environment:
      - ENV=dev
    volumes:
      - ./user-service:/go/src/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"