version: "3.8"

volumes: 
  mongo_data:

services:

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on: 
      - user-service
    ports: 
      - "8080:80"

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      target: builder
    image: user-service
    expose:
      - "8080"
    environment:
      - ENV=dev
      - MONGO_HOST=user-service-mongo
      - MONGO_PORT=27017
    volumes:
      - ./user-service:/go/src/app
    depends_on: 
      - user-service-mongo
    command: ./wait-for.sh user-service-mongo:27017 -- reflex -r "\.go$$" -s -- sh -c "go run ./"

  user-service-mongo:
    container_name: user-service-mongo
    image: mongo
    volumes: 
      - "mongo_data:/data/db"
    expose: 
      - "27017"
    command: mongod --quiet
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=user-service-mongo
    depends_on: 
      - user-service-mongo
