
### login request
# @name loginRequest
POST  http://localhost:8080/api/users/v1/auth/login
Content-Type: application/json

{
    "login":"admin",
    "password": "admin"
}

### response variable
@accessToken = {{loginRequest.response.body.$.accessToken}}

###
GET http://localhost:8080/api/tsodd/v1/helloWorld

###
GET http://localhost:8080/api/tsodd/v1/helloUser
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/tsodd/v1/helloAdmin
Authorization: Bearer {{accessToken}}

### generate new schedule
POST http://localhost:8080/api/tsodd/v1/schedule/generate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "test",
    "resourcesLimit": 10.0,
    "startDate": "2021-05-17",
    "endDate": "2021-05-18"
}

### get list of schedules
GET http://localhost:8080/api/tsodd/v1/schedule?page=1&size=20
Authorization: Bearer {{accessToken}}

### get schedule details
GET http://localhost:8080/api/tsodd/v1/schedule/17?size=2
Authorization: Bearer {{accessToken}}

### create schedule
PUT http://localhost:8080/api/tsodd/v1/schedule
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "test input",
    "startDate": "2021-05-17",
    "endDate": "2021-05-30"
}

### update schedule
PATCH http://localhost:8080/api/tsodd/v1/schedule
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id": "30",
    "name": "test update v2",
    "endDate": "2021-05-29"
}

### delete scedule
DELETE http://localhost:8080/api/tsodd/v1/schedule/41
Authorization: Bearer {{accessToken}}

### create schedules task
PUT http://localhost:8080/api/tsodd/v1/scheduledTask
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "schedule": 17,
    "date": "2021-05-27",
    "tsodd": 8,
    "taskType": 13,
    "crew": 14
}

### update schedules task
PATCH http://localhost:8080/api/tsodd/v1/scheduledTask
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id": 44,
    "schedule": 17,
    "date": "2021-05-27",
    "tsodd": 8,
    "taskType": 13,
    "crew": 14
}

### delete schedules task
DELETE http://localhost:8080/api/tsodd/v1/scheduledTask/100
Authorization: Bearer {{accessToken}}