### login request
# @name loginRequest
POST  http://localhost:8080/api/users/v1/auth/login
Content-Type: application/json

{
    "login":"admin",
    "password": "admin"
}

### response variable
@accessToken = {{loginRequest.response.body.$.accessToken}}


###
GET http://localhost:8080/api/uds/v1/upgradePlan?page=1&size=10
Authorization: Bearer {{accessToken}}

###
PUT http://localhost:8080/api/uds/v1/upgradePlan
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "test input",
    "resourceLimit": 27.0
}

###
DELETE http://localhost:8080/api/uds/v1/upgradePlan/1
Authorization: Bearer {{accessToken}}