
### login request
# @name loginRequest
POST  http://localhost:8080/api/users/v1/auth/login
Content-Type: application/json

{
    "login":"admin",
    "password": "admin"
}

### response variable
@accessToken = {{loginRequest.response.body.$.accessToken}}
@refreshToken = {{loginRequest.response.body.$.refreshToken}}

### token refresh request
# @name tokenRefreshRequest
POST http://localhost:8080/api/users/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### response variable
# @accessToken = {{tokenRefreshRequest.response.body.$.accessToken}}
# @refreshToken = {{tokenRefreshRequest.response.body.$.refreshToken}}

### black list all tokens
POST http://localhost:8080/api/users/v1/auth/logout
Authorization: Bearer {{accessToken}}

### get users roles
GET http://localhost:8080/api/users/v1/roles 

### get users statuses
GET http://localhost:8080/api/users/v1/userStatus 

### get user by id
@userID = 608ed755959e5e674cdb492f
GET http://localhost:8080/api/users/v1/user/{{userID}}
Authorization: Bearer {{accessToken}}

### get list of users
# where page is page nuber default equals 1
#       limit is max users per page
#       role is user roles posible to request user with several roles
#       status is user status

GET http://localhost:8080/api/users/v1/users?page=1&limit=10&&status=ACTIVE&status=DELETED&role=ROLE_USER
Authorization: Bearer {{accessToken}}

### create user
PUT http://localhost:8080/api/users/v1/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "login": "betomex",
    "password": "bkmzbetomex",
    "name": "Ilya",
    "role": [
        "ROLE_USER"
    ]
}

### update user with given id
PATCH  http://localhost:8080/api/users/v1/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id": "6096aebb1495ca60d7c1c76a",
    "login": "betomex",
    "password": "bkmzbetomex",
    "name": "Ilya",
    "role": [
        "ROLE_USER"
    ]
}

### delete user with given id
DELETE http://localhost:8080/api/users/v1/user/607db993fad7324170a4debc
Authorization: Bearer {{accessToken}}